name       : CI Pipeline - DEV
on:
  workflow_dispatch:
  repository_dispatch:
    types: [ deploy-cbr-custom-dev ]
  push:
    branches:
      - dev

env:

  #  PACKAGE_NAME                    : 'cbr_custom_portuguese'

  #  CBR__CUSTOM__ACCOUNT_ID         : '654654216424'
  #  CBR__CONFIG_FILE                : 'cbr-website.community-cbr-hosted.toml'

  #  CBR__CUSTOM__PATH_CUSTOM_CODE   : "./cbr_custom_portuguese/custom"
  #  CBR__CUSTOM__PACKAGES_TO_INSTALL: '["cbr_website_beta", "cbr_content", "cbr_static"]'
  #  S3_DEV__BUCKET                  : "654654216424--cbr-deploy--eu-west-1"
  #  S3_DEV__PARENT_FOLDER           : "cbr-custom-websites"
  GIT__BRANCH                                     : 'dev'
  AWS_ACCESS_KEY_ID                               : ${{ secrets.AWS_ACCESS_KEY_ID__470426667096     }}
  AWS_SECRET_ACCESS_KEY                           : ${{ secrets.AWS_SECRET_ACCESS_KEY__470426667096 }}
  AWS_REGION                                      : 'eu-west-1'
  RELEASE_TYPE                                    : 'minor'
  FLOW__UPDATE_CBR_CUSTOM_ZIP_FILE__S3_BUCKET     : '654654216424--cbr-deploy--eu-west-1'
  FLOW__UPDATE_CBR_CUSTOM_ZIP_FILE__LAMBDA_NAME   : 'dev__cbr_custom_portuguese'
  FLOW__UPDATE_CBR_CUSTOM_ZIP_FILE__S3_KEY        : 'cbr-custom-websites/cbr_website_beta/dev__cbr_custom_portuguese.zip'
  FLOW__UPDATE_CBR_CUSTOM_ZIP_FILE__GH_SOURCE_CODE: 'https://github.com/the-cyber-boardroom/cbr-custom--portuguese/archive/refs/heads/dev.zip'
  FLOW__UPDATE_CBR_CUSTOM_ZIP_FILE__GH_BASE_PATH   : 'cbr-custom--portuguese-dev/cbr__custom_portuguese/custom/'

jobs:

  update-website-content:
    name   : Update Website Content
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: cbr-custom-update-zip-file
        uses: the-cyber-boardroom/cbr-deploy-custom-sites/.github/actions/cbr-custom-update-zip-file@dev


  increment-tag:
    name: Increment Tag - DEV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment Tag (for DEV)
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__increment-tag@dev
        with:
          release_type: ${{ env.RELEASE_TYPE }}
    needs:
      - update-website-content
